# Ingress
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ssp-nodejs-ing
spec:
  rules:
    - host: ssp.k8s.sspcloudpro.co.in
      http:
        paths:
        - backend:
            serviceName: ssp-nodejs-svc
            servicePort: 80
